### ISSUE TITLE
onUpdate function: Accessing a user's preference

### ISSUE THREAD

**Issue by Incantation** [mngl-inc/SampleWithoutReplacement#8]
- function is triggered by a user updating their preferences (an array) on their document.
- function will grab the most recent entry on the array and find that corresponding user in the db.

**Comment by ChefQ** [comment]
Please edit this

**Comment by Incantation** [comment]
> 
> 
> Please edit this

Issues #10 and #11 are created

**Comment by Incantation** [comment]
Code is written up, but needs to be tested.

**Comment by ChefQ** [comment]
Can you test it yourself.

I'm still working on the frontend.

**Comment by ChefQ** [comment]
Elliot learn this:
https://firebase.google.com/docs/functions/unit-testing

**Comment by Incantation** [comment]
I will test it myself, but I have to fix a serious problem with `npm` first. It's giving an error that's never been seen before, and I'm going to reinstall it tomorrow.

**Comment by ChefQ** [comment]
do what you must. However regardless. you have to learn unit-testing. It's essential in platform development.
I will give you send you and issue to learn and implement it.
